### PR TITLE
Update tree.txt

### PR DESCRIPTION
**Pull request by mfaroukgee**

### CODE REVIEW

**Comment by mfaroukg** [comment]
Please let me know how heavy.

**Comment by mfaroukgee** [comment]
estimate 20 kilos

**Comment by mfaroukg** [comment]
I don't have enough trees for this

**Comment by mfaroukgee** [comment]
why is this close

**Comment by mfaroukgee** [comment]
why

**Comment by mfaroukg** [comment]
no need more trees today
come tomorrow for more seeds first

**Comment by mfaroukgee** [comment]
okay

**Pull request merged**
